// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../animus/animus.js', ['animus'], ['goog.dom', 'webgl.App', 'webgl.Renderer']);
goog.addDependency('../../../animus/app.js', ['webgl.App'], []);
goog.addDependency('../../../animus/deps.js', [], []);
goog.addDependency('../../../animus/program.js', ['webgl.Program'], []);
goog.addDependency('../../../animus/renderer.js', ['webgl.Renderer'], []);
goog.addDependency('../../../animus/shader.js', ['webgl.Shader'], []);
