// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../animus/animus.js', ['animus'], ['goog.dom']);
goog.addDependency('../../../animus/app.js', ['animus.App'], []);
goog.addDependency('../../../animus/deps.js', [], []);
goog.addDependency('../../../animus/renderer.js', ['animus.Renderer'], []);
